name: Daily Analysis
on:
  schedule:
    - cron: '0 12 * * *'  # Runs at noon UTC
  workflow_dispatch:  # Allow manual runs

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy python-dotenv
      
      - name: Run analysis
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        run: |
          python research_app.py >> trends.log
          cat trends.log  # Print results
